### ISSUE TITLE
Example code

### ISSUE THREAD

**Issue by mopilo** [sbis04/flutter_bluetooth#2]
I can't run the example code, the app keeps crash. I upgraded to flutter 1.5

**Comment by sbis04** [comment]
This is because the flutter_bluetooth_serial package updated to 0.0.5 from 0.0.4, for which this app was made. There are some changes been made to the plugin which is causing this problem. I am trying to find the solution, in the meanwhile, you can try to contact the person who created the "flutter_bluetooth_serial" package and raise an issue there.

**Comment by sbis04** [comment]
Fixed and Updated the app for flutter_bluetooth_serial 0.0.5
